import java.util.*;
import java.io.*;
import javax.servlet.*;
import javax.servlet.http.*;

public class CookiesTester extends HttpServlet
{
    protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException
    {
        Enumeration<String> param = request.getParameterNames();
        while(param.hasMoreElements())
        {
            String p = param.nextElement().toString();
            response.addCookie(new Cookie(p,request.getParameter(p)));
        }
        response.setContentType("text/html");
        PrintWriter out = response.getWriter();

        out.println("<html><head><title>Cookie Added</title></head>");
        out.println("<body><p>Cookies have been added <a href=\"cookies\">Click Here</a> to see your cookies</p>");
        out.println("<p><a href=\"../html/cookieT.html\">Click here</a> to return to html tester</p></body></html>");
        out.close();
    }

    protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException
    {
        Cookie[] cookies = request.getCookies();
        response.setContentType("text/html");
        PrintWriter out = response.getWriter();

        out.println("<html><head><title>CookieList</title></head>");
        out.println("<body><h3>This page is generated by servlet...</h3>");
        
        if(request.getParameter("delete")!=null)
        {
            for(Cookie c : cookies)
            {
                c.setMaxAge(0);
                response.addCookie(c);
            }
            out.println("<p>All cookies has been deleted has you ask..</p>");
        }
        else
        {
            if(cookies==null) out.println("<p>Here's not cookies... go away >:@</p>");
            else
            {
                out.println("<p>Here's you cookies:<p><br/>");
                for(Cookie c : cookies)
                {  
                    out.println("<p>"+c.getName() +": "+ c.getValue()+"</p>");
                }
            }
        }
            out.println("<br/><p><a href=\"../html/cookieT.html\">Click here</a> to return to tester page!</p>");
            out.println("</body></html>");
            out.close();
    }
}